### ISSUE TITLE
Feature request: pip-installable package with Python API

### ISSUE THREAD

**Issue by iver56** [google/visqol#3] opened 2020-04-15 11:32 UTC
Thanks for making visqol! Would you consider making it easy to install and use in a Python environment?

**Comment by mchinen** [comment] 2020-04-22 16:27
Yes, this is a good feature.  Adding python bindings is planned, and would be a first step in that direction.

**Comment by mpariente** [comment] 2020-06-03 15:37
Great ! 
Do you have any idea of the timeline for that?

**Comment by jonashaag** [comment] 2020-06-18 13:21
I have built and containerised ViSQOL v3 here: https://hub.docker.com/r/jonashaag/visqol

**Comment by jonashaag** [comment] 2020-06-18 13:23
If anyone wants to reproduce the build, here's what I'm using:

Build ViSQOL:

```
FROM ubuntu:18.04

RUN apt update \
 && apt -y install curl gnupg \
 && curl https://bazel.build/bazel-release.pub.gpg | apt-key add - \
 && echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list \
 && apt update && apt -y install git bazel libboost-all-dev
RUN git clone https://github.com/google/visqol \
 && cd visqol \
 && bazel build :visqol -c opt
```

Extract binaries from container:

```
docker cp <container id>:/visqol/bazel-bin/visqol visqol
docker cp <container id>:/visqol/model model
```

Build final image:

```
FROM ubuntu:18.04

COPY visqol /visqol/
COPY model /visqol/model/

WORKDIR /visqol
ENTRYPOINT ["./visqol"]
```

**Comment by mchinen** [comment] 2020-07-24 00:16
Just a heads up I'm working on numpy and protobuf compatible bindings via pybind11, I hope to push to visqol after sorting out some remaining issues.  That would be the precursor to the pip installable package.

**Comment by turian** [comment] 2020-11-02 13:15
Any update on this?

**Comment by mchinen** [comment] 2020-11-06 19:33
Sorry for the delay.  The current status is that we have this working internally, but I am working with the owners of https://github.com/pybind/pybind11_abseil and https://github.com/pybind/pybind11_protobuf.  It's taking a bit to work out the kinks since this is the first external launch of pybind11 for those frameworks, so some general issues need to be resolved first.

**Comment by margaritageleta** [comment] 2021-06-16 14:42
Hi, any update on visqol as python lib? Thaanks

**Comment by iver56** [comment] 2021-06-25 12:23
Since the official python bindings are not ready yet, I made a makeshift python wrapper that uses jonashaag's visqol docker image. It's not very fast, and it's not glamorous, but it works. Check out the python snippet here:

https://gist.github.com/iver56/02daea5f35db744d21bdad2d25c30e22

Hopefully the official python bindings (with less overhead) will be available soon.

**Comment by mchinen** [comment] 2021-06-25 16:47
Thanks @iver56 that's quite interesting, and I hope that unblocks some people.  

The original plan was to use pybind11 for ViSQOL.  Sorry that is taking so much longer than planned.  This is implemented and works internally, but the github version is still not yet pushed - there is currently support for abseil, but not protobuf (https://github.com/pybind/pybind11_protobuf).  However, it is in development.

**Comment by turian** [comment] 2021-06-30 01:02
Docker install for now?

**Comment by seba-plpl** [comment] 2021-09-28 12:52
> Since the official python bindings are not ready yet, I made a makeshift python wrapper that uses jonashaag's visqol docker image. It's not very fast, and it's not glamorous, but it works. Check out the python snippet here:
> 
> https://gist.github.com/iver56/02daea5f35db744d21bdad2d25c30e22
> 
> Hopefully the official python bindings (with less overhead) will be available soon.

Hi,
i tried to use your solution and have following error:
  File "test1.py", line 106, in calculate_visqol_in_audio_mode
    assert degraded_audio.ndim == 2
AttributeError: 'str' object has no attribute 'ndim'

Calling your function, as parameters i'm adding as follow:
calculate_visqol_in_audio_mode(degraded_audio= 'examples_1_processed_16000_Hz.wav',
                               reference_audio= 'examples_1_speech_16000_Hz.wav',sample_rate= 48000) 

what i'm doing wrong/how to solve this issue? Thanks in advance for your help

**Comment by iver56** [comment] 2021-09-28 16:50
It expects numpy arrays (as indicated by the type hints) not strings. Hope this helps.

**Comment by ac0rn0** [comment] 2021-11-02 10:54
I've updated python bindings implementation and fixed Bazel builds for it here #59. So far it works only for Linux. One can build a shared object with `bazel build -c opt //python:pyvisqol.so`. Then use it as a python package (either move it or set PYTHONPATH to the folder with .so). From python:
```python
import pyvisqol
visqol = pyvisqol.ViSQOL("path/to/libsvm_nu_svr_model.txt")  # check usage for more options
# load reference ref and degraded audio deg as a list of floats (1D numpy arrays are also supported)
score = visqol.run(ref, ref_sr, deg, deg_sr)
# or use files directly
score = visqol.run("path/to/reference.wav", "path/to/degraded.wav")
```

**Comment by mchinen** [comment] 2022-04-07 19:00
#66 just merged and has python support (see tests/visqol_lib_py_test.py for examples).  So far it only works on linux and mac.  (I put some effort into Windows, so it builds but fails to import).  This is not a pip-installable package, but presumably this can be used for that.

Thank you @yuribondarenko for the interim python support.

**Comment by deyibo** [comment] 2022-08-10 02:27
So it can't works for windows, what a pity. :(

**Comment by mchinen** [comment] 2022-08-16 19:03
To be clear, Windows works with the normal C++ usage, but the python support is not yet there.  Windows python doesn't work because the pybind11 support was not yet implemented upstream AFAICT. This is not ideal but the other option would be to delay the mac and linux python versions until this was addressed, so I chose to release as is.  If anyone wants to contribute upstream, Windows python support is a great place to make an impact in pybind11_bazel/pybind11_protobuf/pybind11_absl.

**Comment by mchinen** [comment] 2022-12-13 22:38
See #81 which was just merged for a local solution.

**Closed by mchinen** 2022-12-13 22:38 UTC

**Comment by talker93** [comment] 2026-05-26 04:52
Late drop for anyone landing here looking for the original goal of a true `pip install` ViSQOL without Bazel: I just released **[visqol-python](https://pypi.org/project/visqol-python/)** v3.5.0, a pure-Python port of ViSQOL v3.3.3 that works out of the box on Windows / macOS / Linux.

Relevant to this issue's original ask:
- **`pip install visqol-python`** — no Bazel, no system deps, no C++ compilation. Four core PyPI deps (`numpy`, `scipy`, `soundfile`, `libsvm-official`).
- Windows is supported (the upstream pybind11 path still isn't).
- Numerically near C++ parity: 11/11 audio conformance bit-near (≤ 0.0001 MOS diff), speech polynomial diff 0.001, and speech lattice diff 0.0023 against `./bazel-bin/visqol --use_speech_mode` default flags.
- Speech *lattice* (`--use_lattice_model=true`) is supported via the optional `[lattice]` extra (`pip install visqol-python[lattice]`, uses `ai-edge-litert` to load the same `.tflite` model as C++).
- Optional Numba acceleration (`pip install visqol-python[accel]`) brings RTF to ~0.064 (~9× over the pure scipy path).

Apache-2.0, not affiliated with Google. PRs and issues welcome.
